#preload = ~/.config/backgrounds/nature-of-fear.jpg
#wallpaper = eDP-2, ~/.config/backgrounds/nature-of-fear.jpg

wallpaper {
  monitor = eDP-2
  path = ~/.config/backgrounds/nature-of-fear.jpg
  fit_mode = cover
}

splash = false
